export { DeadlinesWidget, FavoritesWidget, SupportWidget, MessagesWidget, CalendarWidget, CourseProgressWidget, ShortcutsWidget } from './DashboardWidgets'
export type { ProcessedDeadline } from './DashboardWidgets'
export { default as ForumAboutWidget } from './ForumAboutWidget'
export { default as ForumActivityWidget } from './ForumActivityWidget'
export { default as ForumWidget } from './ForumWidget'
export { todayEvents, default as QuickOverviewWidget } from './QuickOverviewWidget'
export type { OverviewEvent } from './QuickOverviewWidget'
export { WidgetGrid } from './WidgetGrid'
export { WidgetWrapper } from './WidgetWrapper'
