export { default as CourseModules } from './CourseModules'
export { default as CourseResources } from './CourseResources'
export { default as CourseInfo } from './CourseInfo'
export { default as CourseParticipants } from './CourseParticipants'
export { default as CoursePbl } from './CoursePbl'
export { default as CourseSidebar } from './CourseSidebar'
export { default as CourseBreadcrumbs } from './CourseBreadcrumbs'
export { default as CourseTabContent } from './CourseTabContent'
